[package]
name = "virt-fwk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
block2 = "0.2.0-alpha.8"
crossbeam-channel = "0.5.8"
objc2 = "0.3.0-beta.5"
